name: Курс гривні

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Завантажити код
        uses: actions/checkout@v4

      - name: Встановити Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Встановити залежності
        run: pip install -r requirements.txt

      - name: Запустити бота
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
            - name: Зберегти курс
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add rates.json
          git diff --cached --quiet || git commit -m "Оновлення курсу"
          git pull --rebase origin main
          git push
